server:
  port: 9966

spring:
  application:
    name: EUREKA

eureka:
  instance:
    hostname: localhost   # eureka 实例名称
  client:
    service-url:
      defaultZone: http://localhost:9967/eureka/  # 注册中心访问地址
