server:
  port: 9966

spring:
  application:
    name: EUREKA

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:9967/eureka/  # ????????
