spring:
  application:
    name: CLOUD-ZUUL
server:
  port: 8071
eureka:
  client:
   serviceUrl:
      defaultZone: http://root:123456@localhost:9966/eureka/  # ????????
zuul:
  routes:
    TASKPROVIDER: /task/**
    USERPROVIDER: /user/**



