spring:
  application:
    name: CLOUD-ZUUL
server:
  port: 8071
eureka:
  client:
   serviceUrl:
      defaultZone: http://root:123456@localhost:9966/eureka/  # ????????
zuul:
  routes:
    TASKPROVIDER: /task/**
    USERPROVIDER: /user/**
hystrix:
  command:
    commandKey:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 0