server:
  port: 8091
spring:
  application:
    name: USERPROVIDER
  datasource:
    url: jdbc:mysql://10.222.48.19:3306/todolist?characterEncoding=utf8&useSSL=false
    username: carlos
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@localhost:9966/eureka/

