server:
  port: 9002

spring:
  application:
    name:  SpringCloud-Config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhanghaipin/SpringCloud-Config.git #git仓库配置文件
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9966/eureka/
